### PR TITLE
Add hook CanItemDeployed

### PR DESCRIPTION
**Pull request by rostov114**
Called before the item is deployed.
(Tested, working)

### CODE REVIEW

**Comment by Rostov114** [comment]
Please, delete. Erroneous pull request. Wrong Branch.

**Comment by lukespragg** [comment]
Manually merged, thanks.

**Comment by rostov114** [comment]
Hello. Is it possible to add entityID as a parameter? 
Because when installed in the slot we do not know what BaseEntity he is getting into.

**Comment by lukespragg** [comment]
Yes, I'll look into adding that.

**Comment by lukespragg** [comment]
Both are.

**Comment by rostov114** [comment]
Does Deployable carry Deployer?
It seems the opposite.
Or are there unpublished changes?

**Comment by lukespragg** [comment]
Check the later commits.

**Comment by rostov114** [comment]
I am based on commit 6b3bbc16ce8d33113bd4cf7ae062bda289adb293 and see the addition of the l2 parameter (entityID).
I'm talking about the second parameter.
Those. now we are passing the parameters "BasePlayer, Deployable, entityID".
I mean to transfer the parameters "BasePlayer, Deployer, entityID".

**Comment by lukespragg** [comment]
Changed to as you suggested.

**Pull request closed without merging**
